Change Join / Get Connected links to MeshDB join form
nycmeshnet/nycmesh.net pull request #163
Opened 2024-11-08 05:39 UTC by LydonThorpe

Part of MeshDB deployment. Please approve and wait for roll-out to merge.
Changes /connect and /join to point to the MeshDB join form. Changes the "Get Connected" button in the header.

2024-11-09 22:47 UTC, Andrew-Dickinson requested changes

2024-11-09 22:47 UTC, Andrew-Dickinson commented on netlify.toml
> +force = true
Can we do these in `static/_redirects` instead?

2024-11-11 04:21 UTC, LydonThorpe commented
moved redirects to /static/_redirects based on feedback

2024-11-23 04:16 UTC, Andrew-Dickinson approved these changes

2024-11-23 04:16 UTC, Andrew-Dickinson commented on static/_redirects
> +/es/join https://forms.nycmesh.net/join
```suggestion
/es/join https://forms.nycmesh.net/es/join/
```

2024-11-23 04:16 UTC, Andrew-Dickinson commented on static/_redirects
> +/zh/join https://forms.nycmesh.net/join
```suggestion
/zh/join https://forms.nycmesh.net/zh/join/
```

2024-11-24 01:22 UTC, merged